workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.example.translatorplus"
      java: 17
    scripts:
      - name: Grant execute permission to gradlew
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
