
workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.example.translatorplus"
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
